name: Build lavat binaries

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Alpine build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y alpine-sdk

      - name: Build lavat for Alpine
        run: |
          mkdir lavat-alpine
          cp lavat.c lavat-alpine/
          cd lavat-alpine
          gcc -static -o lavat lavat.c

      - name: Upload Linux Alpine binary
        uses: actions/upload-artifact@v4
        with:
          name: lavat-linux-alpine
          path: lavat-alpine/lavat

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW
        run: choco install mingw --no-progress

      - name: Add MinGW to PATH (correct way)
        run: |
          echo "C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Build lavat.exe
        run: gcc -o lavat.exe lavat.c

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: lavat-windows-exe
          path: lavat.exe
