name: Build Lavat Windows and Alpine Linux binaries

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install MinGW
        run: choco install mingw

      - name: Add MinGW to PATH
        shell: powershell
        run: echo "::add-path::C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin"

      - name: Build Windows EXE with gcc
        run: |
          gcc -o lavat.exe lavat.c   # Adjust source files list if more than one

      - name: Upload Windows EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: lavat-windows-exe
          path: lavat.exe

  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Alpine toolchain and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools build-essential gcc make pkg-config

      - name: Build static binary for Alpine
        run: |
          musl-gcc -static -o lavat lavat.c  # Adjust source files if needed

      - name: Upload Alpine binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: lavat-alpine-binary
          path: lavat
